version: '3.4'

services:
  gshop_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "45432:5432"
    networks:
      - shared_gshop_net
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  gshop_rabbitmq:
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672" 
    networks:
      - shared_gshop_net
    volumes:      
      - ./rabbitmq:/var/lib/rabbitmq
    command: >
      bash -c "chown rabbitmq:rabbitmq /var/lib/rabbitmq/.erlang.cookie && chmod 400 /var/lib/rabbitmq/.erlang.cookie && rabbitmq-server"
    
  gshop_api:
    ports:
      - "10000:8080"
    networks:
      - shared_gshop_net
    env_file:
      - env.api

  gshop_identity:
    ports:
      - "10001:8080"
    networks:
      - shared_gshop_net
    env_file:
      - env.identity

  gshop_email_1:
    networks:
      - shared_gshop_net
    ports:
      - "10003:8080"
    env_file:
      - env.email


networks:
  shared_gshop_net:
    name: gshop
    driver: bridge