version: '3.4'

services:

  gshop_postgresql:
    image: postgres:14.1    
    
  gshop_rabbitmq:
    image: rabbitmq:management
            
  gshop_api:
    image: ${DOCKER_REGISTRY-}gshopapi
    build:
      context: .
      dockerfile: Systems/Api/GShop.Api/Dockerfile
    depends_on:
      - gshop_postgresql
      - gshop_rabbitmq

  gshop_identity:
    image: ${DOCKER_REGISTRY-}gshopidentity
    build:
      context: .
      dockerfile: Systems/Identity/GShop.Identity/Dockerfile
    depends_on:
      - gshop_postgresql
      - gshop_api

  gshop_worker_1:
    image: ${DOCKER_REGISTRY-}gshopworker
    build:
      context: .
      dockerfile: Systems/Workers/GShop.Worker/Dockerfile
    depends_on:
      - gshop_postgresql
      - gshop_rabbitmq
      - gshop_api
